### DISCUSSION TITLE
Any known documentation as tests tooling around bats-core?

### DISCUSSION THREAD

**Discussion by djmcgreal-cc** [bats-core/bats-core#694] [General]
Hi,
We've been very happily using bats as our go-to tool for all things testing. We'd like to start aligning our documentation with the tests themselves, so that, when presented to users, we've a fair chance of it working and being consistent with the rest of the application.

Is anyone aware of any frameworks for such that synergise with bats, etc?

Specifically we're doing a lot of Kubernetes API testing.

Thanks! Dan.

**Comment by martin-schulze-vireso** [comment]
Do you have an example of what you mean from another language/test framework?

**Comment by djmcgreal-cc** [comment]
I'm just getting into researching the tools, so thought I'd ask in this community (as ideally what we use would have the consistent reporting control and consistency) for anything I should look at (I'm finding Google fairly noisy). I found https://github.com/anko/txm.

When I think about what I'd like ideally, I think I'd like some script to parse a markdown document's front matter for something like

```yaml
bats:
  setup_file:
    heading: Setup
  tests:
    - heading: Create a Pod that authenticates against the GitLab API
      asserts: kubectl wait --for condition=...
    - heading: Create a Pod that performs git operations
  teardown_file:
    script: kubectl delete -l documentation-tests
```

Then use remark or mdast or so to generate a bats test script from the code blocks found in the headings configured.

Ideally the test could be generated from bats. I don't know what happens if bats generates a bats test file in e.g. setup_suite or so and then includes it?
