### ISSUE TITLE
GitLab CI -  Error: BATS_TMPDIR (/tmp) is not writable

### ISSUE THREAD

**Issue by cavo789** [bats-core/bats-core#564]
Hello

I can't start bats in a GitLab CI, each time I got `Error: BATS_TMPDIR (/tmp) is not writable`. I've tried to change the target folder but nothing works. 

My `.gitlab-ci.yml` file:

```yaml
variables:
  GIT_SUBMODULE_STRATEGY: recursive 
  TMPDIR: "${CI_PROJECT_DIR}/.tmp"
  BATS_TMPDIR: "${CI_PROJECT_DIR}/.tmp"

stages:
  - test
 
bats:
  stage: test
  image: bash:5.1.16-alpine3.15
  script:
    before_script:
    - echo "BATS_TMPDIR IS **${BATS_TMPDIR}***"
    - mkdir -p "${BATS_TMPDIR}" && chmod 777 "${BATS_TMPDIR}"
    - ls -alh
    - ./test/bats/bin/bats --version
    script:
    - ./test/bats/bin/bats ./test
```

**Environment:**
 - Bats Version 1.6.0
 - OS: Linux
 - Bash version: 5.1.16

As you can see below, the `BATS_TMPDIR` folder is set to my current working folder and I've create the folder (`mkdir -p`) and change his permissions to `777`.  The image show that the folder is created with the correct permission but, neverthless, I continue to get the "is not writable" message.

![2022-04-07_15h28_52](https://user-images.githubusercontent.com/355999/162210329-3a5a65a4-e6f0-4fa0-b80b-a3670e5b2e8b.png)

Did you see where I'm wrong? 

(I've also tried to use the Docker image `https://hub.docker.com/r/bats/bats`  but I was unable too to make it working i.e. which command should I run because `bats` seems unknown)

**Comment by cavo789** [comment]
Will check tomorrow. Thanks for your really fast answer.

**Comment by martin-schulze-vireso** [comment]
I tried to reproduce this locally with bats-core checked out at v1.6.0 and using the following adapted `.gitlab-ci.yml`:

```
variables:
  GIT_SUBMODULE_STRATEGY: recursive 
  TMPDIR: "${CI_PROJECT_DIR}/.tmp"
  BATS_TMPDIR: "${CI_PROJECT_DIR}/.tmp"

stages:
  - test
 
bats:
  stage: test
  image: bash:5.1.16-alpine3.15
  before_script:
    - echo "BATS_TMPDIR IS **${BATS_TMPDIR}***"
    - mkdir -p "${BATS_TMPDIR}" && chmod 777 "${BATS_TMPDIR}"
    - ls -alh
    - ./bin/bats --version
  script:
    - ./bin/bats ./test
```

However, the tests ran as expected.
