### ISSUE TITLE
Formatter repeating output (Github Actions)

### ISSUE THREAD

**Issue by polarathene** [bats-core/bats-core#639]
**Describe the bug**

Attempted to use the `--pretty` formatter in Github Actions CI. I referenced usage of [`TERM: linux` used in this projects own GHA workflows](https://github.com/bats-core/bats-core/blob/c97b3a1b8644ddede18bff6bc035c12e9f50be78/.github/workflows/tests.yml#L41), but I'm getting a weird mix of pretty and tap output?

![Screenshot_20220822_211541](https://user-images.githubusercontent.com/5098581/185887715-e84bd93d-6399-4164-8a24-54f171c7052a.png)

**To Reproduce**

Relevant step in CI workflow to run bats:

```yml
- name: 'Run tests'
    env:
      TERM: linux
    run: |
      # Calls bats via make if that makes a difference,
      # The `bash -c` isn't likely necessary and was contributed by another user prior:
      bash -c 'make generate-accounts tests'
```

`Makefile` runs bats with the following:

```
./test/bats/bin/bats --timing --pretty test/*.bats
```

**Expected behavior**

Output similar to using the pretty formatter locally. Not repeated content.

**Environment (please complete the following information):**
 - Bats Version: 1.7
 - OS: Ubuntu 20.04 (Github CI runner)
 - Bash version: ? (_Not sure, but equivalent to `bats-core` workflow_)

**Additional context**

Regular tap worked fine without `--pretty`. Enabling `--pretty` failed due to lack of `$TERM`, checked `bats-core` project for related issues/solutions to find `TERM: linux`.

If this is an issue with Github CI not capable of supporting `--pretty` that's fine :+1:

**Comment by martin-schulze-vireso** [comment]
This is an intermittent bug in the pretty formatter. A have seen that too but was not able to reproduce it reliably.

If you can reproduce this, could you please use `--report-formatter cat` and post the resulting `report.log` here?

**Comment by polarathene** [comment]
> but was not able to reproduce it reliably.

My current workflow runs have been reproducing it reliably :sweat_smile: 

Step now looks like:

```yml
- name: 'Run tests'
    env:
      TERM: linux
    run: |
      NAME=mailserver-testing:ci
      make generate-accounts
      test/bats/bin/bats --report-formatter cat --pretty test/mail_time.bats
      cat report.log
```

Here is the log output of the step:
```
mail_time.bats
   checking time: setting the time with TZ works correctly1/1 ✓ checking time: setting the time with TZ works correctly

1 test, 0 failures

1..1
suite /home/runner/work/dms-test/dms-test/test/mail_time.bats
begin 1 checking time: setting the time with TZ works correctly
ok 1 checking time: setting the time with TZ works correctly
```

This is no different to the `report.log` from local runs without the repetition shown in screenshot from CI.

---

The test being handled is:

```bash
load 'test_helper/common'

setup_file() {
  local PRIVATE_CONFIG
  PRIVATE_CONFIG=$(duplicate_config_for_container .)

  docker run -d --name mail_time \
    -v "${PRIVATE_CONFIG}":/tmp/docker-mailserver \
    -v "$(pwd)/test/test-files":/tmp/docker-mailserver-test:ro \
    -e TZ='Asia/Jakarta' \
    -e LOG_LEVEL=debug \
    -h mail.my-domain.com -t "${NAME}"

  wait_for_smtp_port_in_container mail_time
}

teardown_file() {
  docker rm -f mail_time
}

@test "checking time: setting the time with TZ works correctly" {
  run docker exec mail_time cat /etc/timezone
  assert_success
  assert_output 'Asia/Jakarta'

  run docker exec mail_time date '+%Z'
  assert_success
  assert_output 'WIB'
}
```
